apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.mongo.pvc.name }}
  namespace: {{ .Values.namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.mongo.pvc.storage }}
