apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: production-chat

type: Opaque

stringData:
  JWT_SECRET: chatapp_super_secret_jwt_key_2026
  MONGO_URI: mongodb://admin:Admin%40123@mongo-service:27017/chatapp?authSource=admin
